name: user_repository
description: UserRepository for flutter_login.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  shared_preferences: ^0.5.0
  dota_notifier:
    path: ..